/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package excel;

import java.io.IOException;
import java.net.URISyntaxException;

public class App {

    public static void main(String[] args) throws IOException, URISyntaxException {
        new ExcelWorker().start();
    }

}
